[library.axi]
location = fusesoc/designs/axi

[library.modulo]
location = fusesoc/designs/modulo

[library.cross]
location = fusesoc/designs/cross

[library.misc]
location = fusesoc/designs/misc

[library.sha3]
location = fusesoc/designs/sha3

[library.fpga]
location = fusesoc/fpga

[library.test]
location = fusesoc/test
